name: test
on: push
jobs:

  test-ts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          cd ../tools/local-env
          docker-compose up -d

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install deps
        run: npm ci

      - name: start server
        run: |
          npm run build
          npm start &
        env:
          FCLI_TLS_PATH: '../tools/local-env/cert'

      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin

      - name: run tests
        run: |
          cd ..
          ./test/test.sh

  test-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          cd ../tools/local-env
          docker-compose up -d

      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: start server
        run: go run . &
        env:
          FCLI_TLS_PATH: '../tools/local-env/cert'

      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin

      - name: run tests
        run: |
          cd ..
          ./test/test.sh

  test-kt:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.repository_owner }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ./kotlin
    steps:
      - uses: actions/checkout@v3

      - name: setup env
        run: |
          cd ../tools/local-env
          docker-compose up -d

      - name: install cli
        run: |
          curl https://raw.githubusercontent.com/findy-network/findy-agent-cli/HEAD/install.sh > install.sh
          chmod a+x install.sh
          sudo ./install.sh -b /bin

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: build server
        run: gradle build

      - name: start server
        run: gradle bootRun &
        env:
          FCLI_TLS_PATH: '../tools/local-env/cert'

      - name: run tests
        run: |
          cd ..
          ./test/test.sh